webSitePath = "Data/Website/"
lastPhotoPath = "Data/Website/Images/lastPhoto.png"
knockValuePath = "Data/KnockValue"
laserDelayValuePath = "Data/LaserDelayValue"
logPath = "Data/log.txt"
targetPath = "Data/Targets/"